baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'quia'
theme = "quia"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "main"

URL = ""


[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true


[markup.tableOfContents]
  startLevel = 2 # Or whatever starting heading level you prefer
  endLevel = 3   # Or whatever ending heading level you prefer
  ordered = true
  
  
[markup]
  [markup.highlight]
    noClasses = false
    lineNumbersInTable = false
    linenos = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)'], ['\(', '\)']] # Ensure '$' is here